version: '2'

services:

  php:
    image: javanile/lamp:7.0
    env_file:
      - development.env
    volumes:
      - ./:/var/www/html:rw
    ports:
      - "38080:80"
    links:
      - mysql
    restart: "no"

  mysql:
    image: mysql:5.5
    env_file:
      - development.env
    restart: "no"

  adminer:
    image: javanile/adminer
    env_file:
      - development.env
    ports:
      - "38081:8080"
    links:
      - mysql
    restart: "no"
