version: '2'

services:

  php:
    image:    javanile/lamp:7.0
    env_file: ['services.env']
    volumes:  ['./:/var/www/html:rw']
    ports:    ['38080:80']
    links:    ['mysql']

  mysql:
    image:    mysql:5.5
    env_file: ['services.env']

  adminer:
    image:    javanile/adminer
    env_file: ['services.env']
    ports:    ['38081:8080']
    links:    ['mysql']
